/**
 * Geography ladder data (E.3.2). Server-side, so no app-size budget.
 *
 * MVP seed table: major US + CA cities → containing state/province.
 * Replace with a full GeoNames-derived table before launch. Anything NOT
 * found here is treated as finer-than-city → REDACT (fail closed).
 */
export const GEO_TABLE_VERSION = 'seed-0.1';

export const CITY_TO_REGION: Record<string, string> = {
  // Canada
  toronto: 'Ontario',
  ottawa: 'Ontario',
  mississauga: 'Ontario',
  hamilton: 'Ontario',
  london: 'Ontario',
  montreal: 'Quebec',
  'quebec city': 'Quebec',
  laval: 'Quebec',
  gatineau: 'Quebec',
  vancouver: 'British Columbia',
  victoria: 'British Columbia',
  surrey: 'British Columbia',
  burnaby: 'British Columbia',
  calgary: 'Alberta',
  edmonton: 'Alberta',
  winnipeg: 'Manitoba',
  saskatoon: 'Saskatchewan',
  regina: 'Saskatchewan',
  halifax: 'Nova Scotia',
  "st. john's": 'Newfoundland and Labrador',
  fredericton: 'New Brunswick',
  charlottetown: 'Prince Edward Island',
  // United States
  'new york': 'New York',
  'new york city': 'New York',
  buffalo: 'New York',
  'los angeles': 'California',
  'san francisco': 'California',
  'san diego': 'California',
  'san jose': 'California',
  sacramento: 'California',
  oakland: 'California',
  chicago: 'Illinois',
  houston: 'Texas',
  dallas: 'Texas',
  austin: 'Texas',
  'san antonio': 'Texas',
  'fort worth': 'Texas',
  phoenix: 'Arizona',
  tucson: 'Arizona',
  philadelphia: 'Pennsylvania',
  pittsburgh: 'Pennsylvania',
  columbus: 'Ohio',
  cleveland: 'Ohio',
  cincinnati: 'Ohio',
  indianapolis: 'Indiana',
  charlotte: 'North Carolina',
  raleigh: 'North Carolina',
  seattle: 'Washington',
  spokane: 'Washington',
  denver: 'Colorado',
  boston: 'Massachusetts',
  nashville: 'Tennessee',
  memphis: 'Tennessee',
  detroit: 'Michigan',
  portland: 'Oregon',
  'las vegas': 'Nevada',
  baltimore: 'Maryland',
  milwaukee: 'Wisconsin',
  albuquerque: 'New Mexico',
  'kansas city': 'Missouri',
  'st. louis': 'Missouri',
  atlanta: 'Georgia',
  miami: 'Florida',
  orlando: 'Florida',
  tampa: 'Florida',
  jacksonville: 'Florida',
  'new orleans': 'Louisiana',
  minneapolis: 'Minnesota',
  'salt lake city': 'Utah',
  anchorage: 'Alaska',
  honolulu: 'Hawaii',
};

export const REGIONS = new Set([
  // Canadian provinces & territories
  'ontario',
  'quebec',
  'british columbia',
  'alberta',
  'manitoba',
  'saskatchewan',
  'nova scotia',
  'new brunswick',
  'newfoundland and labrador',
  'prince edward island',
  'yukon',
  'northwest territories',
  'nunavut',
  // US states
  'alabama',
  'alaska',
  'arizona',
  'arkansas',
  'california',
  'colorado',
  'connecticut',
  'delaware',
  'florida',
  'georgia',
  'hawaii',
  'idaho',
  'illinois',
  'indiana',
  'iowa',
  'kansas',
  'kentucky',
  'louisiana',
  'maine',
  'maryland',
  'massachusetts',
  'michigan',
  'minnesota',
  'mississippi',
  'missouri',
  'montana',
  'nebraska',
  'nevada',
  'new hampshire',
  'new jersey',
  'new mexico',
  'new york',
  'north carolina',
  'north dakota',
  'ohio',
  'oklahoma',
  'oregon',
  'pennsylvania',
  'rhode island',
  'south carolina',
  'south dakota',
  'tennessee',
  'texas',
  'utah',
  'vermont',
  'virginia',
  'washington',
  'west virginia',
  'wisconsin',
  'wyoming',
]);

export const COUNTRIES = new Set([
  'canada',
  'united states',
  'usa',
  'america',
  'united states of america',
  'mexico',
  'france',
  'germany',
  'italy',
  'spain',
  'portugal',
  'united kingdom',
  'england',
  'scotland',
  'wales',
  'ireland',
  'japan',
  'china',
  'india',
  'brazil',
  'australia',
  'netherlands',
  'belgium',
  'switzerland',
  'austria',
  'sweden',
  'norway',
  'denmark',
  'finland',
  'poland',
  'russia',
  'ukraine',
  'turkey',
  'egypt',
  'south africa',
  'nigeria',
  'kenya',
  'argentina',
  'chile',
  'colombia',
  'peru',
  'south korea',
  'vietnam',
  'thailand',
  'philippines',
  'indonesia',
  'pakistan',
  'bangladesh',
  'israel',
  'saudi arabia',
  'greece',
]);

export type GeoGranularity = 'country' | 'region' | 'city' | 'finer';

export function classifyLocation(text: string): {
  granularity: GeoGranularity;
  region?: string;
} {
  const normalized = text.toLowerCase().trim();
  if (COUNTRIES.has(normalized)) return { granularity: 'country' };
  if (REGIONS.has(normalized)) return { granularity: 'region' };
  const region = CITY_TO_REGION[normalized];
  if (region) return { granularity: 'city', region };
  // Unknown location string → treat as finer than city (fail closed).
  return { granularity: 'finer' };
}
